### PR TITLE
Add direct3d shaderc support on linux

### PR DESCRIPTION
**Pull request by MRNIU**
To adapt to the changes in 
https://github.com/bkaradzic/bgfx/commit/4c0baf5603626b328e25c26b23b1e0ceda029178 and https://github.com/bkaradzic/bgfx/commit/f14c14a48554de4e66a4b2334f623d988c06f36d

### CODE REVIEW

**Comment by bwrsandman** [comment]
Looks like you left some dx9 references.

**Comment by MRNIU** [comment]
@bwrsandman cleared, thank you

**Comment by bwrsandman** [comment]
Seems to be failing because the commited submodules are from before https://github.com/bkaradzic/bgfx/commit/f14c14a48554de4e66a4b2334f623d988c06f36d.
Normally, at the start of every month, I update the submodules with dependabot.

The PR by dependabot should open tomorrow, so I will test and merge these two tomorrow.

**Comment by bwrsandman** [comment]
This command on linux does not work. Do you know why?
```
$ build/cmake/bgfx/shaderc -f bgfx/examples/01-cubes/vs_cubes.sc -i bgfx/src -o bgfx/examples/runtime/shaders/dx11/vs_cubes.bin --platform windows --type vertex --profile s_5_0 -O 3
HLSL compiler is not supported on this platform.
Failed to build shader.
```

**Comment by MRNIU** [comment]
It seems that shaderc where not support d3d on linux yet(`SHADERC_CONFIG_HLSL` is false, shaderc.h#L15). Maybe we should take up this issue?

**Comment by bwrsandman** [comment]
Does it make sense then to add `s_4_0` and `s_5_0` to the linux platform given that fail?

**Comment by bwrsandman** [comment]
Doing some testing, it seems like it tries to load d3d11.so and when it can't find it, it loads another renderer.
I believe this only happens on WSL but I could be wrong.

**Comment by bwrsandman** [comment]
After a month of inactivity, I'm closing this PR.
Feel free to re-open it if you have updates!

**Pull request closed without merging**
