### PR TITLE
Update bgfx.cmake to work with Emscripten

### PR DESCRIPTION
**Pull request by pr0g**
While working with bgfx.cmake and Emscripten I ran into an issue building using `emcmake`. For full details please see this comment and thread - https://github.com/pr0g/sdl-bgfx-imgui-starter/pull/8#issuecomment-903835951.

This change resolves the problem, there may be another way to solve this but this definitely improves the current state of things.

Thanks for your time,

Tom

### CODE REVIEW

**Comment by pr0g** [comment]
Thanks @bwrsandman 👍

**Comment by bwrsandman** [comment]
@pr0g, I was getting errors about max texture layers being exceeded when I tried bgfx last week. Do you think this would fix it?

**Comment by pr0g** [comment]
Hey @bwrsandman, sorry I'm just responding. Hmm I'm afraid I don't think those things are related, my change was purely related to Emscripten and it sounds like you were seeing something else. What platform and backend were you using?

**Comment by bwrsandman** [comment]
WebGL. It turns out bgfx flat out disables texture arrays in WebGL.

**Comment by hultonha** [comment]
Ah I see 😅 Well that'll do it 😝

**Pull request merged**
